CREATE TABLE IF NOT EXISTS Users (
user_id INTEGER generated by default as identity NOT NULL,
email VARCHAR,
login VARCHAR,
birthday DATE,
PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS Film (
film_id INTEGER generated by default as identity NOT NULL,
name VARCHAR,
description VARCHAR,
releaseDate DATE,
duration INTEGER,
likesCount INTEGER,
rating VARCHAR,
PRIMARY KEY (film_id)
);

CREATE TABLE IF NOT EXISTS Genre (
genre_id INTEGER generated by default as identity NOT NULL,
name VARCHAR,
PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS Users_Friends (
user_id INTEGER,
friend_id INTEGER,
FOREIGN KEY (user_id) REFERENCES Users(user_id),
FOREIGN KEY (friend_id) REFERENCES Users(user_id),
PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS Film_Genre (
film_id INTEGER,
genre_id INTEGER,
FOREIGN KEY (film_id) REFERENCES Film(film_id),
FOREIGN KEY (genre_id) REFERENCES Genre(genre_id),
PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS Likes (
film_id INTEGER,
user_id INTEGER,
FOREIGN KEY (film_id) REFERENCES Film(film_id),
FOREIGN KEY (user_id) REFERENCES Users(user_id),
PRIMARY KEY (film_id, user_id)
)